### ISSUE TITLE
Refactor API to use serverless framework

### ISSUE THREAD

**Issue by trent-howard** [zootytooty/ZootAPI#1]
This should make it easier to do a bunch of stuff

* deployment
* define routes and handlers
* setup API Gateway validation for route parameters and query strings
* enable CORS if we ever want to make a fetch from a web front-end
* setup API keys or an IP allow list

**Comment by diabolical-ninja** [comment]
#4 Addresses:

- ~~deployment~~
- ~~define routes and handlers~~

Separate issues created for:
- #5 setup API Gateway validation for route parameters and query strings
- #6:  enable CORS if we ever want to make a fetch from a web front-end
-  #7 setup API keys or an IP allow list
